apiVersion: batch/v1
kind: Job
metadata:
  name: tf-gpu-test-job-0
spec:
  template:
    spec:
      containers:
      - name: tf-gpu-test-job
        image: tf-gpu-test:latest
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
      restartPolicy: Never
  backoffLimit: 4  