apiVersion: v1
kind: Pod
metadata:
  name: check-gpu
spec:
  restartPolicy: Never
  containers:
  - name: gpu-container
    image: nvidia/cuda:10.0-runtime
    command:
      - "/bin/sh"
      - "-c"
    args:
      - nvidia-smi
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
