apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-gpu-mnist

spec:
  restartPolicy: Never
  containers:
  - name: tensorflow-gpu-mnist
    args:
    - sleep
    - "100000"
    image: mnist-container:latest
    imagePullPolicy: Always
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
