apiVersion: v1
kind: Pod
metadata:
  name: tensorflow

spec:
  containers:
  - args:
    - sleep
    - "100000"
    image: tensorflow/tensorflow
    imagePullPolicy: Always
    name: tensorflow
  restartPolicy: Never

