apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-gpu
spec:
  restartPolicy: Never
  containers:
  - name: tensorflow
    args:
    - python
    - "-c"
    - "import tensorflow as tf; print(\"TEST:\", tf.reduce_sum(tf.random.normal([1000, 1000])))"
    image: tensorflow/tensorflow:latest-gpu
    imagePullPolicy: Always
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1