apiVersion: batch/v1
kind: Job
metadata:
  name: tf-gpu-mnist-job-0
spec:
  template:
    spec:
      containers:
      - name: tf-gpu-mnist-job
        # image: image-registry.openshift-image-registry.svc:5000/sbergste-cuda/tf-gpu-mnist:latest
        image: tf-gpu-mnist:latest
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
      restartPolicy: Never
  backoffLimit: 4
